on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - name: Hello world action step
        id: hello
        uses: simonmisencik/gitops-environment-propagation@main
        with:
          source_enviroment: 'staging'
          destination_enviroment: 'production'
          prefix_folder: 'environments'
          suffix_folder: 'app'
