# Promote a GitOps application from one environment to the next

name: Environment propagation

on:
  workflow_dispatch:
    inputs:
      source_env:
        description: 'Source environment'
        required: true
        default: 'staging' 
        type: choice
        options:
        - staging
        - production
      target_env:
        description: 'Target environment'
        required: true
        default: 'production' 
        type: choice
        options:
        - staging
        - production

jobs:
  promote:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - name: Propagate changes and create PR
        id: hello
        uses: simonmisencik/gitops-environment-propagation@main
        with:
          source_enviroment: 'staging'
          target_enviroment: 'production'
          prefix_folder: 'environments'
          suffix_folder: 'app'
